backend/urls.py
#!/usr/bin/env python
__author__ = 'Chocolee'


"""tsck_demo URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.urls import path
from backend.views import login as loginview
from backend.views import user as userview
from backend.views import order as orderview
from backend.views import assets as assetsview
from backend.views import deploy as deployview

urlpatterns = [
    path('index.html', loginview.index),
    path('login-out.html', loginview.login_out),
    path('403.html', loginview.status_403),
    path('personal-info.html', loginview.personal_info),

    path('user.html', userview.index_user),
    path('add-user.html', userview.add_user),
    path('del-user.html', userview.del_user),
    path('edit-user.html', userview.edit_user),

    path('order.html', orderview.index_order),
    path('create-order.html', orderview.create_order),
    path('get-detail.html', orderview.get_detail),
    path('del-order.html', orderview.del_order),
    path('edit-order.html', orderview.edit_order),
    path('ops-handle-order.html', orderview.ops_handle_order),
    path('test-handle-order.html', orderview.test_handle_order),

    # path('assets-json.html', assetsview.AssetsJsonView.as_view()),
    path('assets.html', assetsview.AssetsView.as_view()),
    path('add-assets.html', assetsview.AssetsAddView.as_view()),
    path('edit-assets.html', assetsview.AssetsEditView.as_view()),
    path('gateone-auth.html', assetsview.AssetsGateOneAuthView.as_view()),

    path('deploy-cmd.html', deployview.DeployCmdView.as_view()),
    path('task-result.html', deployview.task_result),
    path('deploy-batch.html', deployview.DeployBatchView.as_view()),
    path('deploy-run.html', deployview.deploy_run),

]

tsck_demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('backend/', include('backend.urls')),
    path('web/', include('web.urls')),
]

web/urls.py
#!/usr/bin/env python
__author__ = 'Chocolee'

"""tsck_demo URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from web import views as vweb
from backend import views  as vbackend

urlpatterns = [
    path('login.html', vweb.login),
    path('api.html', vweb.api),
]

repository/models.py
from django.db import models

# Create your models here.


######################用户管理########################
class User(models.Model):
    """用户表"""
    username = models.CharField(max_length=32, unique=True)
    password = models.CharField(max_length=64)
    realname = models.CharField(max_length=64)
    sex_choices = (
        (0, '女'),
        (1, '男'),
    )
    sex = models.SmallIntegerField(choices=sex_choices, default=0)
    email = models.EmailField(max_length=64)
    phone = models.IntegerField()
    position = models.CharField(max_length=64, blank=True, null=True)
    date = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = '用户表'

    def __str__(self):
        return self.username


class Role(models.Model):
    """角色表"""
    caption = models.CharField(max_length=32)

    class Meta:
        verbose_name_plural = '角色表'

    def __str__(self):
        return self.caption


class User2Role(models.Model):
    """用户和角色权限对应表，多对多关系"""
    u = models.ForeignKey(User, on_delete=models.CASCADE)
    r = models.ForeignKey(Role, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '用户分配角色'
        unique_together = ('u', 'r')

    def __str__(self):
        return "%s-%s" %(self.u.username, self.r.caption)


class Menu(models.Model):
    """菜单表"""
    caption = models.CharField(max_length=32)
    parent = models.ForeignKey('self', related_name='p',null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '菜单表'

    def __str__(self):
        return "%s" % (self.caption,)


class Permission(models.Model):
    """权限表"""
    caption = models.CharField(max_length=32)
    url = models.CharField(max_length=32)
    icon = models.CharField(max_length=64)
    menu = models.ForeignKey(Menu,null=True,blank=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'URL权限表'

    def __str__(self):
        return "%s-%s" % (self.caption, self.url)


class Permission2Role(models.Model):
    """角色对权限，多对多，由于为内部运维工具，不再细化到增删改查粒度，只到URL的权限控制粒度"""
    p = models.ForeignKey(Permission, on_delete=models.CASCADE)
    r = models.ForeignKey(Role, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '角色分配权限'
        unique_together = ('p', 'r')

    def __str__(self):
        return "%s==>%s" %(self.r.caption, self.p,)


######################工单管理########################
class Projects(models.Model):
    """项目列表，比如招行项目，兴业项目"""
    project_name = models.CharField(max_length=32, unique=True)
    host_to_remote_users = models.ManyToManyField("HostToRemoteUser")

    class Meta:
        verbose_name_plural = '项目列表'

    def __str__(self):
        return "%s" % (self.project_name,)


class Envlists(models.Model):
    """各个环境列表（比如测试环境，生产环境等）"""
    env = models.CharField(max_length=32, unique=True)

    class Meta:
        verbose_name_plural = '环境列表'

    def __str__(self):
        return "%s" % (self.env,)


class Workorders(models.Model):
    """工单管理表"""
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=32)
    detail = models.TextField()
    project_name = models.ForeignKey(Projects, on_delete=models.CASCADE)
    env_label = models.ForeignKey(Envlists, on_delete=models.CASCADE)
    create_time = models.DateTimeField(auto_now_add=True)
    handler = models.ForeignKey(User, on_delete=models.CASCADE, related_name='h', null=True, blank=True)
    handler_role_status = (
        (1, '运维工程师'),
        (2, '测试工程师'),
        (3, '开发工程师'),
        (4, '无'),
    )
    handler_role = models.IntegerField(choices=handler_role_status, default=1)
    handle_time = models.DateTimeField(null=True, blank=True)
    handle_status_choices = (
        (1, '未处理'),
        (2, '处理中'),
        (3, '已处理'),
        (4, '废单'),
    )
    handle_status = models.IntegerField(choices=handle_status_choices, default=1)
    ops_result = models.TextField(null=True, blank=True)
    test_result = models.TextField(null=True, blank=True)
    role_status_choices = (
        (1, '开发工程师'),
        (2, '运维工程师'),
        (3, '测试工程师'),
    )
    role_status = models.IntegerField(choices=role_status_choices, default=1)

    class Meta:
        verbose_name_plural = '工单列表'

    def __str__(self):
        return "%s" % (self.title,)


######################资产管理########################
class IDC(models.Model):
    """机房信息"""
    name = models.CharField(max_length=64, unique=True)

    class Meta:
        verbose_name_plural = 'IDC机房'

    def __str__(self):
        return "%s" % (self.name,)


class Host(models.Model):
    """存储主机列表"""
    hostname = models.CharField(max_length=64,unique=True)
    ip_address = models.GenericIPAddressField(unique=True)
    port = models.SmallIntegerField(default=22)
    idc = models.ForeignKey("IDC", on_delete=models.CASCADE, blank=True, null=True)
    assets_type_choices = (
        (1, '虚拟机'),
        (2, '交换机'),
        (3, '服务器'),
        (4, '防火墙'),
    )
    assets_type = models.SmallIntegerField(choices=assets_type_choices, default=1)
    project_name = models.ForeignKey("Projects", on_delete=models.CASCADE, blank=True, null=True)
    env_type = models.ForeignKey("Envlists", on_delete=models.CASCADE, blank=True, null=True)
    cpu = models.CharField(max_length=32)
    disk = models.CharField(max_length=32)
    memory = models.CharField(max_length=32)

    def __str__(self):
        return self.hostname

    class Meta:
        verbose_name_plural = '主机列表'


class RemoteUser(models.Model):
    """存储远程要管理的主机的账号信息"""
    auth_type_choices = ((0, 'ssh-password'), (1, 'ssh-key'))
    auth_type = models.SmallIntegerField(choices=auth_type_choices, default=0)
    username = models.CharField(max_length=32)
    password = models.CharField(max_length=64, blank=True, null=True)

    class Meta:
        unique_together = ('auth_type', 'username', 'password')
        verbose_name_plural = '远程主机账号密码表'

    def __str__(self):
        return "%s:%s" %(self.username, self.password)


class HostToRemoteUser(models.Model):
    """绑定主机和远程用户的对应关系"""
    host = models.ForeignKey("Host", on_delete=models.CASCADE)
    remote_user = models.ForeignKey("RemoteUser", on_delete=models.CASCADE)
    role = models.ForeignKey("Role", on_delete=models.CASCADE)

    class Meta:
        unique_together = ("host", "remote_user")
        verbose_name_plural = '主机对应远程账号密码表'

    def __str__(self):
        return "%s %s"%(self.host.ip_address, self.remote_user)


######################部署管理########################
class Task(models.Model):
    """批量任务"""
    task_type_choices = (('cmd','批量命令'),('file-transfer','文件传输'))
    task_type = models.CharField(choices=task_type_choices,max_length=64)
    content = models.CharField(max_length=255, verbose_name="任务内容")
    user = models.ForeignKey("User", on_delete=models.CASCADE)

    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s %s"%(self.task_type,self.content)

    class Meta:
        verbose_name_plural = '批量任务表'


class TaskLogDetail(models.Model):
    """存储大任务子结果"""
    task = models.ForeignKey("Task", on_delete=models.CASCADE)
    host_to_remote_user = models.ForeignKey("HostToRemoteUser", on_delete=models.CASCADE)
    result = models.TextField(verbose_name="任务执行结果")
    status_choices = ((0,'initialized'),(1,'success'),(2,'failed'),(3,'timeout'))
    status = models.SmallIntegerField(choices=status_choices,default=0)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s %s"%(self.task,self.host_to_remote_user)

    class Meta:
        verbose_name_plural = '批量任务子结果表'


class AppVersion(models.Model):
    """应用模块版本"""
    version = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.version

    class Meta:
        verbose_name_plural = '应用模块版本号'


class AppModuleList(models.Model):
    """应用模块列表"""
    name = models.CharField(max_length=64, unique=True)
    jenkins_url = models.CharField(max_length=256)
    jenkins_jobs_name = models.CharField(max_length=64)
    deploy_path = models.CharField(max_length=64)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '应用模块列表'


class AppToHostToRemoteUser(models.Model):
    """应用对应主机列表"""
    a = models.ForeignKey('AppModuleList', on_delete=models.CASCADE)
    h = models.ForeignKey('HostToRemoteUser', on_delete=models.CASCADE)

    def __str__(self):
        return "%s-%s@%s" % (self.a.name, self.h.remote_user.username, self.h.host.ip_address)

    class Meta:
        unique_together = ("a", "h")
        verbose_name_plural = '应用对应主机列表'

backend/views/assets.py
#!/usr/bin/env python
__author__ = 'Chocolee'

from backend.views.login import *
from utils.get_argv import *
from django.http import JsonResponse
from django.views import View



class AssetsView(View):

    def get(self, request, *args, **kwargs):
        request_info = AssetsGetArgv(request)
        request_info.auth_user()
        if request_info.status():
            render_argv = request_info.base_render_argv()
            render_argv['page_obj'] = request_info.get_host_paper()['page_obj']
            render_argv['data_list'] = request_info.get_host_paper()['data_list']
            return render(
                request, 'backend/backend_assets.html', render_argv)
        else:
            return redirect('/backend/403.html')


class AssetsAddView(View):

    def get(self, request, *args, **kwargs):
        request_info = AssetsGetArgv(request)
        request_info.auth_user()
        if request_info.status():
            render_argv = request_info.base_render_argv()
            render_argv['forms_add_asset'] = request_info.forms_add_asset
            return render(request, 'backend/backend_add_assets.html', render_argv)
        else:
            return redirect('/backend/403.html')

    def post(self, request, *args, **kwargs):
        request_info = AssetsGetArgv(request)
        request_info.auth_user()
        if request_info.status():
            if request_info.forms_add_asset_to_db() is True:
                return redirect('/backend/assets.html')
            else:
                render_argv = request_info.base_render_argv()
                render_argv['forms_add_asset'] = request_info.forms_add_asset_to_db()
                return render(request, 'backend/backend_add_assets.html', render_argv)
        else:
            return redirect('/backend/403.html')


class AssetsEditView(View):

    def get(self, request, *args, **kwargs):
        request_info = AssetsGetArgv(request)
        request_info.auth_user()
        nid = request.GET.get('nid')
        action = request.GET.get('Action')
        if request_info.status():
            render_argv = request_info.base_render_argv()
            if action == "编辑":
                forms_edit_asset = request_info.forms_edit_asset(nid)
                render_argv['forms_edit_asset'] = forms_edit_asset
                render_argv['nid'] = nid
                return render(request, 'backend/backend_edit_assets.html', render_argv)
            elif action == "连接":
                """不写了，webssh有点不怎么好用，这边可以
                通过nid找到这条host记录，通过登录用户及连表找到相应权限的用户进行登录，就是一个damo测试"""
                render_argv['ip'] = '192.168.31.100'
                render_argv['port'] = 22
                render_argv['username'] = 'dev'
                return render(request, 'backend/backend_gateone.html', render_argv)
            else:
                return redirect('/backend/assets.html')
        else:
            return redirect('/backend/403.html')

    def post(self, request, *args, **kwargs):
        request_info = AssetsGetArgv(request)
        request_info.auth_user()
        nid = request.POST.get('nid')
        action = request.POST.get('Action')
        if request_info.status():
            if action == "提交":
                if request_info.forms_edit_asset_to_db(nid) is True:
                    return redirect('/backend/assets.html')
                else:
                    render_argv = request_info.base_render_argv()
                    render_argv['forms_edit_asset'] = request_info.forms_edit_asset_to_db(nid)
                    return render(request, 'backend/backend_edit_assets.html', render_argv)
            elif action == "删除这条记录":
                result = request_info.del_asset(nid)
                if result:
                    return redirect('/backend/assets.html')
                else:
                    return HttpResponse(result)
            else:
                pass
        else:
            return redirect('/backend/403.html')


class AssetsGateOneAuthView(View):

    def get(self,request, *args, **kwargs):
        request_info = AssetsGetArgv(request)
        request_info.auth_user()
        '''
        gateone继承到web界面上
        :return:返回gateone url及认证参数
        '''
        # 安装gateone的服务器以及端口.
        gateone_server = 'https://192.168.31.100:443'
        # 之前生成的api_key 和secret
        api_key = 'ZDlmOTkzMjlhNDc4NDY5Y2I1M2I0MzQwNGU4ZmM1OTNmM'
        secret = 'ZjlhOWZkY2JlZjlkNGUzOGIyNDc5ZmQ4ODNiYTI1MjM3M'
        authobj = {
            'api_key': api_key,
            'upn': 'gateone',
            'timestamp': str(int(time.time() * 1000)),
            'signature_method': 'HMAC-SHA1',
            'api_version': '1.0'
        }
        authobj['signature'] = request_info.create_signature(secret, authobj['api_key'], authobj['upn'], authobj['timestamp'])
        auth_info_and_server = {'url': gateone_server, 'auth': authobj}
        print(1)
        return JsonResponse(auth_info_and_server)



# class AssetsJsonView(View):
#
#     def get(self, request, *args, **kwargs):
#         request_info = GetArgvHelper(request)
#         request_info.auth_user()
#
#         if request_info.status():
#             data_list = data_list_all()
#
#             result = {
#                 'table_config': table_config,
#                 'data_list': list(data_list),
#                 'global_dict': {
#                     'assets_type_choices': models.Host.assets_type_choices,
#                 }
#             }
#             return HttpResponse(json.dumps(result))
#         else:
#             return redirect('/backend/403.html')

templates/backend/backend_assets.html
{% extends 'backend/backend_index.html' %}

{% block pro_name %}{{ menu_info.0 }}{% endblock %}

{% block pro_in_name %}{{ menu_info.0 }}{% endblock %}

{% block icon_name %}{{ menu_info.1 }}{% endblock %}

{% block icon_in_name %}{{ menu_info.1 }}{% endblock %}

{% block this_url %}{{ menu_info.2 }}{% endblock %}



{% block page_body %}

    <div class="panel-body">

        <a class="btn btn-primary right" href="add-assets.html" role="button" style="margin-bottom: 10px">新建主机</a>

        <div style="display: inline-block; float: right" class="dataTables_filter" id="datatable1_filter">
            <form method="get" action="assets.html">
                {% csrf_token %}
                <label>
                    <div style="display: inline-block; float: left;margin-right: 5px">
                        <input type="search" class="form-control input-large" name="q" placeholder="支持IP地址及项目" aria-controls="datatable1">
                    </div>
                    <div style="display: inline-block; float: right">
                        <button type="submit" class="btn btn-default" >搜索</button>
                    </div>
                </label>
            </form>
        </div>


        <table class="table table-bordered" id="assetsInfoId">
            <thead id="table_th">
                <tr>
                    <th>IP地址</th>
                    <th>资产类型</th>
                    <th><a href="#">所属项目</a></th>
                    <th><a href="#">所属环境</a></th>
                    <th>CPU</th>
                    <th>内存</th>
                    <th>硬盘</th>
                    <th><a href="#">IDC机房</a></th>
                    <th>操作</th>
                </tr>
            </thead>

            <tbody id="table_tb">

            {% for row in data_list %}
                <tr nid="{{ row.id }}">
                    <td>{{ row.ip_address}}</td>
                    <td>{{ row.get_assets_type_display }}</td>
                    <td>{{ row.project_name.project_name }}</td>
                    <td>{{ row.env_type.env }}</td>
                    <td>{{ row.cpu }}</td>
                    <td>{{ row.memory }}</td>
                    <td>{{ row.disk }}</td>
                    <td>{{ row.idc.name }}</td>
                    <td>
                        <form  action="edit-assets.html" method="GET"  novalidate>
                            <input name="nid" style="display: none" value="{{ row.id }}">
                            <input Type="Submit" class="btn btn-primary btn-xs assets-edit-row" name="Action" value="编辑">
                            |
                            <input Type="Submit" class="btn btn-dark btn-xs web-ssh" name="Action" value="连接">

                        </form>

                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>

        <div class="dataTables_paginate paging_bs_full">
            <ul class="pagination left small" style="margin-top: 0">
                {{ page_obj.page_str|safe }}
            </ul>
        </div>


    </div>

{% endblock %}

templates/backend/backend_dev_order.html
{% extends 'backend/backend_index.html' %}

{% block pro_name %}{{ menu_info.0 }}{% endblock %}

{% block pro_in_name %}{{ menu_info.0 }}{% endblock %}

{% block icon_name %}{{ menu_info.1 }}{% endblock %}

{% block icon_in_name %}{{ menu_info.1 }}{% endblock %}

{% block this_url %}{{ menu_info.2 }}{% endblock %}



{% block page_body %}

    <div class="panel-body">

        <a class="btn btn-primary right" href="#" id="createOrderId" role="button">创建工单</a>

        <div style="display: inline-block; float: right" class="dataTables_filter" id="datatable1_filter">
            <form method="get" action="#">
                {% csrf_token %}
                <label>
                    <div style="display: inline-block; float: left;margin-right: 5px">
                        <input type="search" class="form-control input-large" name="q" placeholder="只支持标题"
                               aria-controls="datatable1">
                    </div>
                    <div style="display: inline-block; float: right">
                        <button type="submit" class="btn btn-default">搜索</button>
                    </div>
                </label>
            </form>
        </div>


        <table class="table table-bordered" id="orderInfoId">
            <thead>
            <tr>
                <th>工单标题</th>
                <th>项目名称</th>
                <th>变更环境</th>
                <th>状态</th>
                <th>创建时间</th>
                <th>处理者</th>
                <th>NEXT执行角色</th>
                <th>处理时间</th>
                <th>操作</th>
            </tr>
            </thead>

            <tbody>

            {% for row in work_list %}
                <tr nid="{{ row.id }}">
                    <td na="nid" style="display: none">{{ row.id }}</td>
                    <td na="detail" style="display: none">{{ row.detail }}</td>
                    {% if row.title|length >= 10 %}
                        <td na="title">{{ row.title|slice:"10" }}...</td>
                    {% else %}
                        <td na="title">{{ row.title}}</td>
                    {% endif %}
                    <td na="project_name" pid="{{ row.project_name.id }}">{{ row.project_name.project_name }}</td>
                    <td na="env" eid="{{ row.env_label.id }}">{{ row.env_label.env }}</td>
                    <td>{{ row.get_handle_status_display }}</td>
                    <td>{{ row.create_time|date:"Y-m-d H:i:s" }}</td>
                    <td uid="{{ row.creator.id }}"><a href="#" class="show-user-info">{{ row.handler.realname }}</a>
                    </td>
                    <td>{{ row.get_handler_role_display }}</td>
                    <td>{{ row.handle_time|date:"Y-m-d H:i:s" }}</td>
                    <td>

                        {% if row.handle_status == 1 and row.role_status == 1 %}
                            <a class="btn btn-primary btn-xs dev-order-edit-row" href="#">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                编辑
                            </a>
                            |
                            <a class="btn btn-danger btn-xs dev-order-del-row">
                                <i class="fa fa-times" aria-hidden="true"></i>
                                删除
                            </a>
                        {% else %}
                            {% if row.role_status == 2 %}
                                <a class="btn btn-info btn-xs ops-result-show" href="#">
                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                    运维已变更
                                </a>
                            {% elif row.role_status == 3 %}
                                {% if row.handle_status == 4 %}
                                    <a class="btn btn-pink btn-xs test-result-show" href="#">
                                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                        功能验证失败
                                    </a>
                                {% else %}
                                    <a class="btn btn-success btn-xs test-result-show" href="#">
                                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                        测试完成
                                    </a>
                                {% endif %}
                            {% endif %}
                        {% endif %}


                    </td>
                </tr>

            {% endfor %}


            </tbody>
        </table>

        <div class="dataTables_paginate paging_bs_full">
            <ul class="pagination left small" style="margin-top: 0">
                {{ page_obj.page_str|safe }}
            </ul>
        </div>


    </div>

{% endblock %}

templates/backend/backend_ops_order.html
{% extends 'backend/backend_index.html' %}

{% block pro_name %}{{ menu_info.0 }}{% endblock %}

{% block pro_in_name %}{{ menu_info.0 }}{% endblock %}

{% block icon_name %}{{ menu_info.1 }}{% endblock %}

{% block icon_in_name %}{{ menu_info.1 }}{% endblock %}

{% block this_url %}{{ menu_info.2 }}{% endblock %}



{% block page_body %}

    <div class="panel-body">


        <div style="display: inline-block; float: right" class="dataTables_filter" id="datatable1_filter">
            <form method="get" action="#">
                {% csrf_token %}
                <label>
                    <div style="display: inline-block; float: left;margin-right: 5px">
                        <input type="search" class="form-control input-large" name="q" placeholder="只支持标题" aria-controls="datatable1">
                    </div>
                    <div style="display: inline-block; float: right">
                        <button type="submit" class="btn btn-default" >搜索</button>
                    </div>
                </label>
            </form>
        </div>



        <table class="table table-bordered" id="otherOrderId">
            <thead>
            <tr>
                <th>工单标题</th>
                <th>项目名称</th>
                <th>变更环境</th>
                <th>状态</th>
                <th>创建者</th>
                <th>创建时间</th>
                <th>处理者</th>
                <th>操作</th>
            </tr>
            </thead>

            <tbody>

            {% for row in work_list %}
                <tr nid="{{ row.id }}">
                    <td na="nid" style="display: none">{{ row.id }}</td>
                    <td na="detail" style="display: none">{{ row.detail }}</td>
                    {% if row.title|length >= 10 %}
                        <td na="title" ><a href="#" class="show-detail-ok">{{ row.title|slice:"10" }}...</a></td>
                    {% else %}
                        <td na="title" ><a href="#" class="show-detail-ok">{{ row.title }}</a></td>
                    {% endif %}
                    <td na="project_name" pid="{{ row.project_name.id }}">{{ row.project_name.project_name }}</td>
                    <td na="env" eid="{{ row.env_label.id }}">{{ row.env_label.env }}</td>
                    <td>{{ row.get_handle_status_display }}</td>
                    <td uid="{{ row.creator.id }}"><a href="#" class="show-creator-info">{{ row.creator.realname }}</a></td>
                    <td>{{ row.create_time|date:"Y-m-d H:i:s" }}</td>
                    <td uid="{{ row.handler.id }}"><a href="#" class="show-handler-info">{{ row.handler.realname }}</a></td>
                    <td>
                        {% if row.handle_status == 1 and row.role_status == 1 %}
                            <a class="btn btn-purple btn-xs ops-order-edit-row" href="#">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                处理
                            </a>
                        {% else %}
                            {% if row.role_status == 2 %}
                                <a class="btn btn-info btn-xs ops-result-show" href="#">
                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                    运维已变更
                                </a>
                            {% elif row.role_status == 3 %}
                                {% if row.handle_status == 4 %}
                                    <a class="btn btn-pink btn-xs test-result-show" href="#">
                                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                        功能验证失败
                                    </a>
                                {% else %}
                                    <a class="btn btn-success btn-xs test-result-show" href="#">
                                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                        测试完成
                                    </a>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>

            {% endfor %}


            </tbody>
        </table>

        <div class="dataTables_paginate paging_bs_full">
            <ul class="pagination left small" style="margin-top: 0">
                {{ page_obj.page_str|safe }}
            </ul>
        </div>


    </div>

{% endblock %}